#!/bin/bash
tar -cvf /root/sda1.tar /home
mount /dev/sda1 /mnt
if [-e /mnt/check_mount]
then
echo "File Already"
else
echo "Mounting device /dev/sda1 - /mnt"
mount /dev/sda1/mnt
fi
rm -R /mnt/sda1.tar
